/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package io.typefox.yang.yang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Belongs To</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.yang.yang.BelongsTo#getModule <em>Module</em>}</li>
 * </ul>
 *
 * @see io.typefox.yang.yang.YangPackage#getBelongsTo()
 * @model
 * @generated
 */
public interface BelongsTo extends OtherStatement
{
  /**
   * Returns the value of the '<em><b>Module</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Module</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Module</em>' reference.
   * @see #setModule(Module)
   * @see io.typefox.yang.yang.YangPackage#getBelongsTo_Module()
   * @model
   * @generated
   */
  Module getModule();

  /**
   * Sets the value of the '{@link io.typefox.yang.yang.BelongsTo#getModule <em>Module</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Module</em>' reference.
   * @see #getModule()
   * @generated
   */
  void setModule(Module value);

} // BelongsTo
