/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package io.typefox.yang.yang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bit</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see io.typefox.yang.yang.YangPackage#getBit()
 * @model
 * @generated
 */
public interface Bit extends Enumerable
{
} // Bit
