/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package io.typefox.yang.yang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Current Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.yang.yang.CurrentRef#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see io.typefox.yang.yang.YangPackage#getCurrentRef()
 * @model
 * @generated
 */
public interface CurrentRef extends XpathStep
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ref</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(SchemaNode)
   * @see io.typefox.yang.yang.YangPackage#getCurrentRef_Ref()
   * @model
   * @generated
   */
  SchemaNode getRef();

  /**
   * Sets the value of the '{@link io.typefox.yang.yang.CurrentRef#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(SchemaNode value);

} // CurrentRef
