/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package io.typefox.yang.yang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Default</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.yang.yang.Default#getDefaultStringValue <em>Default String Value</em>}</li>
 * </ul>
 *
 * @see io.typefox.yang.yang.YangPackage#getDefault()
 * @model
 * @generated
 */
public interface Default extends OtherStatement
{
  /**
   * Returns the value of the '<em><b>Default String Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Default String Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Default String Value</em>' attribute.
   * @see #setDefaultStringValue(String)
   * @see io.typefox.yang.yang.YangPackage#getDefault_DefaultStringValue()
   * @model
   * @generated
   */
  String getDefaultStringValue();

  /**
   * Sets the value of the '{@link io.typefox.yang.yang.Default#getDefaultStringValue <em>Default String Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Default String Value</em>' attribute.
   * @see #getDefaultStringValue()
   * @generated
   */
  void setDefaultStringValue(String value);

} // Default
