/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package io.typefox.yang.yang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fraction Digits</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.yang.yang.FractionDigits#getRange <em>Range</em>}</li>
 * </ul>
 *
 * @see io.typefox.yang.yang.YangPackage#getFractionDigits()
 * @model
 * @generated
 */
public interface FractionDigits extends OtherStatement
{
  /**
   * Returns the value of the '<em><b>Range</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Range</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Range</em>' attribute.
   * @see #setRange(String)
   * @see io.typefox.yang.yang.YangPackage#getFractionDigits_Range()
   * @model
   * @generated
   */
  String getRange();

  /**
   * Sets the value of the '{@link io.typefox.yang.yang.FractionDigits#getRange <em>Range</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Range</em>' attribute.
   * @see #getRange()
   * @generated
   */
  void setRange(String value);

} // FractionDigits
