/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package io.typefox.yang.yang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Include</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see io.typefox.yang.yang.YangPackage#getInclude()
 * @model
 * @generated
 */
public interface Include extends AbstractImport
{
} // Include
