/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package io.typefox.yang.yang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Key Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.yang.yang.KeyReference#getNode <em>Node</em>}</li>
 * </ul>
 *
 * @see io.typefox.yang.yang.YangPackage#getKeyReference()
 * @model
 * @generated
 */
public interface KeyReference extends EObject
{
  /**
   * Returns the value of the '<em><b>Node</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Node</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node</em>' reference.
   * @see #setNode(Leaf)
   * @see io.typefox.yang.yang.YangPackage#getKeyReference_Node()
   * @model
   * @generated
   */
  Leaf getNode();

  /**
   * Sets the value of the '{@link io.typefox.yang.yang.KeyReference#getNode <em>Node</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node</em>' reference.
   * @see #getNode()
   * @generated
   */
  void setNode(Leaf value);

} // KeyReference
