/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package io.typefox.yang.yang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Min Elements</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.yang.yang.MinElements#getMinElements <em>Min Elements</em>}</li>
 * </ul>
 *
 * @see io.typefox.yang.yang.YangPackage#getMinElements()
 * @model
 * @generated
 */
public interface MinElements extends OtherStatement
{
  /**
   * Returns the value of the '<em><b>Min Elements</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Min Elements</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Min Elements</em>' attribute.
   * @see #setMinElements(String)
   * @see io.typefox.yang.yang.YangPackage#getMinElements_MinElements()
   * @model
   * @generated
   */
  String getMinElements();

  /**
   * Sets the value of the '{@link io.typefox.yang.yang.MinElements#getMinElements <em>Min Elements</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Min Elements</em>' attribute.
   * @see #getMinElements()
   * @generated
   */
  void setMinElements(String value);

} // MinElements
