/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package io.typefox.yang.yang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Other Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see io.typefox.yang.yang.YangPackage#getOtherStatement()
 * @model
 * @generated
 */
public interface OtherStatement extends Statement
{
} // OtherStatement
