/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package io.typefox.yang.yang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Path</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.yang.yang.Path#getReference <em>Reference</em>}</li>
 * </ul>
 *
 * @see io.typefox.yang.yang.YangPackage#getPath()
 * @model
 * @generated
 */
public interface Path extends OtherStatement
{
  /**
   * Returns the value of the '<em><b>Reference</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Reference</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reference</em>' containment reference.
   * @see #setReference(XpathExpression)
   * @see io.typefox.yang.yang.YangPackage#getPath_Reference()
   * @model containment="true"
   * @generated
   */
  XpathExpression getReference();

  /**
   * Sets the value of the '{@link io.typefox.yang.yang.Path#getReference <em>Reference</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reference</em>' containment reference.
   * @see #getReference()
   * @generated
   */
  void setReference(XpathExpression value);

} // Path
