/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package io.typefox.yang.yang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Refine</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.yang.yang.Refine#getNode <em>Node</em>}</li>
 * </ul>
 *
 * @see io.typefox.yang.yang.YangPackage#getRefine()
 * @model
 * @generated
 */
public interface Refine extends OtherStatement
{
  /**
   * Returns the value of the '<em><b>Node</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Node</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node</em>' containment reference.
   * @see #setNode(SchemaNodeIdentifier)
   * @see io.typefox.yang.yang.YangPackage#getRefine_Node()
   * @model containment="true"
   * @generated
   */
  SchemaNodeIdentifier getNode();

  /**
   * Sets the value of the '{@link io.typefox.yang.yang.Refine#getNode <em>Node</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node</em>' containment reference.
   * @see #getNode()
   * @generated
   */
  void setNode(SchemaNodeIdentifier value);

} // Refine
