/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package io.typefox.yang.yang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.yang.yang.Statement#getSubstatements <em>Substatements</em>}</li>
 * </ul>
 *
 * @see io.typefox.yang.yang.YangPackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends EObject
{
  /**
   * Returns the value of the '<em><b>Substatements</b></em>' containment reference list.
   * The list contents are of type {@link io.typefox.yang.yang.Statement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Substatements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Substatements</em>' containment reference list.
   * @see io.typefox.yang.yang.YangPackage#getStatement_Substatements()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getSubstatements();

} // Statement
