/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package io.typefox.yang.yang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.yang.yang.TypeReference#getBuiltin <em>Builtin</em>}</li>
 *   <li>{@link io.typefox.yang.yang.TypeReference#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see io.typefox.yang.yang.YangPackage#getTypeReference()
 * @model
 * @generated
 */
public interface TypeReference extends EObject
{
  /**
   * Returns the value of the '<em><b>Builtin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Builtin</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Builtin</em>' attribute.
   * @see #setBuiltin(String)
   * @see io.typefox.yang.yang.YangPackage#getTypeReference_Builtin()
   * @model
   * @generated
   */
  String getBuiltin();

  /**
   * Sets the value of the '{@link io.typefox.yang.yang.TypeReference#getBuiltin <em>Builtin</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Builtin</em>' attribute.
   * @see #getBuiltin()
   * @generated
   */
  void setBuiltin(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(Typedef)
   * @see io.typefox.yang.yang.YangPackage#getTypeReference_Type()
   * @model
   * @generated
   */
  Typedef getType();

  /**
   * Sets the value of the '{@link io.typefox.yang.yang.TypeReference#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(Typedef value);

} // TypeReference
