/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package io.typefox.yang.yang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unknown</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.yang.yang.Unknown#getExtension <em>Extension</em>}</li>
 *   <li>{@link io.typefox.yang.yang.Unknown#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see io.typefox.yang.yang.YangPackage#getUnknown()
 * @model
 * @generated
 */
public interface Unknown extends OtherStatement
{
  /**
   * Returns the value of the '<em><b>Extension</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Extension</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Extension</em>' reference.
   * @see #setExtension(Extension)
   * @see io.typefox.yang.yang.YangPackage#getUnknown_Extension()
   * @model
   * @generated
   */
  Extension getExtension();

  /**
   * Sets the value of the '{@link io.typefox.yang.yang.Unknown#getExtension <em>Extension</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Extension</em>' reference.
   * @see #getExtension()
   * @generated
   */
  void setExtension(Extension value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see io.typefox.yang.yang.YangPackage#getUnknown_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link io.typefox.yang.yang.Unknown#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // Unknown
