/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package io.typefox.yang.yang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>When</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.yang.yang.When#getCondition <em>Condition</em>}</li>
 * </ul>
 *
 * @see io.typefox.yang.yang.YangPackage#getWhen()
 * @model
 * @generated
 */
public interface When extends OtherStatement
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(XpathExpression)
   * @see io.typefox.yang.yang.YangPackage#getWhen_Condition()
   * @model containment="true"
   * @generated
   */
  XpathExpression getCondition();

  /**
   * Sets the value of the '{@link io.typefox.yang.yang.When#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(XpathExpression value);

} // When
