/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package io.typefox.yang.yang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Xpath Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see io.typefox.yang.yang.YangPackage#getXpathExpression()
 * @model
 * @generated
 */
public interface XpathExpression extends EObject
{
} // XpathExpression
