/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package io.typefox.yang.yang.impl;

import io.typefox.yang.yang.DataSchemaNode;
import io.typefox.yang.yang.YangPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Data Schema Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DataSchemaNodeImpl extends SchemaNodeImpl implements DataSchemaNode
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DataSchemaNodeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return YangPackage.Literals.DATA_SCHEMA_NODE;
  }

} //DataSchemaNodeImpl
