/**
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package io.typefox.yang.yang.impl;

import io.typefox.yang.yang.XpathExpression;
import io.typefox.yang.yang.XpathLocation;
import io.typefox.yang.yang.XpathStep;
import io.typefox.yang.yang.YangPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Xpath Location</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.yang.yang.impl.XpathLocationImpl#getTarget <em>Target</em>}</li>
 *   <li>{@link io.typefox.yang.yang.impl.XpathLocationImpl#isIsDescendants <em>Is Descendants</em>}</li>
 *   <li>{@link io.typefox.yang.yang.impl.XpathLocationImpl#getStep <em>Step</em>}</li>
 * </ul>
 *
 * @generated
 */
public class XpathLocationImpl extends XpathExpressionImpl implements XpathLocation
{
  /**
   * The cached value of the '{@link #getTarget() <em>Target</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTarget()
   * @generated
   * @ordered
   */
  protected XpathExpression target;

  /**
   * The default value of the '{@link #isIsDescendants() <em>Is Descendants</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsDescendants()
   * @generated
   * @ordered
   */
  protected static final boolean IS_DESCENDANTS_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isIsDescendants() <em>Is Descendants</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isIsDescendants()
   * @generated
   * @ordered
   */
  protected boolean isDescendants = IS_DESCENDANTS_EDEFAULT;

  /**
   * The cached value of the '{@link #getStep() <em>Step</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStep()
   * @generated
   * @ordered
   */
  protected XpathStep step;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected XpathLocationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return YangPackage.Literals.XPATH_LOCATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public XpathExpression getTarget()
  {
    return target;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTarget(XpathExpression newTarget, NotificationChain msgs)
  {
    XpathExpression oldTarget = target;
    target = newTarget;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, YangPackage.XPATH_LOCATION__TARGET, oldTarget, newTarget);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTarget(XpathExpression newTarget)
  {
    if (newTarget != target)
    {
      NotificationChain msgs = null;
      if (target != null)
        msgs = ((InternalEObject)target).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - YangPackage.XPATH_LOCATION__TARGET, null, msgs);
      if (newTarget != null)
        msgs = ((InternalEObject)newTarget).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - YangPackage.XPATH_LOCATION__TARGET, null, msgs);
      msgs = basicSetTarget(newTarget, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, YangPackage.XPATH_LOCATION__TARGET, newTarget, newTarget));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isIsDescendants()
  {
    return isDescendants;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIsDescendants(boolean newIsDescendants)
  {
    boolean oldIsDescendants = isDescendants;
    isDescendants = newIsDescendants;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, YangPackage.XPATH_LOCATION__IS_DESCENDANTS, oldIsDescendants, isDescendants));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public XpathStep getStep()
  {
    return step;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetStep(XpathStep newStep, NotificationChain msgs)
  {
    XpathStep oldStep = step;
    step = newStep;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, YangPackage.XPATH_LOCATION__STEP, oldStep, newStep);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStep(XpathStep newStep)
  {
    if (newStep != step)
    {
      NotificationChain msgs = null;
      if (step != null)
        msgs = ((InternalEObject)step).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - YangPackage.XPATH_LOCATION__STEP, null, msgs);
      if (newStep != null)
        msgs = ((InternalEObject)newStep).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - YangPackage.XPATH_LOCATION__STEP, null, msgs);
      msgs = basicSetStep(newStep, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, YangPackage.XPATH_LOCATION__STEP, newStep, newStep));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case YangPackage.XPATH_LOCATION__TARGET:
        return basicSetTarget(null, msgs);
      case YangPackage.XPATH_LOCATION__STEP:
        return basicSetStep(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case YangPackage.XPATH_LOCATION__TARGET:
        return getTarget();
      case YangPackage.XPATH_LOCATION__IS_DESCENDANTS:
        return isIsDescendants();
      case YangPackage.XPATH_LOCATION__STEP:
        return getStep();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case YangPackage.XPATH_LOCATION__TARGET:
        setTarget((XpathExpression)newValue);
        return;
      case YangPackage.XPATH_LOCATION__IS_DESCENDANTS:
        setIsDescendants((Boolean)newValue);
        return;
      case YangPackage.XPATH_LOCATION__STEP:
        setStep((XpathStep)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case YangPackage.XPATH_LOCATION__TARGET:
        setTarget((XpathExpression)null);
        return;
      case YangPackage.XPATH_LOCATION__IS_DESCENDANTS:
        setIsDescendants(IS_DESCENDANTS_EDEFAULT);
        return;
      case YangPackage.XPATH_LOCATION__STEP:
        setStep((XpathStep)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case YangPackage.XPATH_LOCATION__TARGET:
        return target != null;
      case YangPackage.XPATH_LOCATION__IS_DESCENDANTS:
        return isDescendants != IS_DESCENDANTS_EDEFAULT;
      case YangPackage.XPATH_LOCATION__STEP:
        return step != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (isDescendants: ");
    result.append(isDescendants);
    result.append(')');
    return result.toString();
  }

} //XpathLocationImpl
