/*
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package io.typefox.yang.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class YangAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("io/typefox/yang/parser/antlr/internal/InternalYangParser.tokens");
	}
}
