/**
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package io.typefox.yang;

import io.typefox.yang.YangStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class YangStandaloneSetup extends YangStandaloneSetupGenerated {
  public static void doSetup() {
    new YangStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
